# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abc24cdb53cc91d3971f3748d4ff9ed9734b34b35309160e4b6a153c9a7e8c4756192cd1be19a92c7fbf3b530d9de32fb6d92ae72be4a441ae2be3f38e163fac

test:
  secret_key_base: 4e2464d618d2142548413723d5effcd60c4ea24ee833e2b38340cedf9a64b8f26caea52e93173f7795bbff5f383f99f56f2edae97deff0a4eaf455fbe15f8a9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
